### ISSUE TITLE
Errors in ODataConnectedService.Tests project

### ISSUE THREAD

**Issue by unchase** [OData/ODataConnectedService#41]
### Describe the bug
There are a few identical errors occured in `ODataConnectedService.Tests` project:

In `CodeGenCommandlineSetNamespacePrefixRepeatWithSchemaNameSpace`, `CodeGenCommandlineSetNamespacePrefixWithSingleNamespace` and `CodeGenCommandlineSimpleEdmx` tests:

> Message: Метод теста ODataConnectedService.Tests.ODataT4CodeGeneratorTests.CodeGenCommandlineSetNamespacePrefixRepeatWithSchemaNameSpace создал исключение: 
    FluentAssertions.Execution.AssertionFailedException: Expected empty string, but found "c:\<path>\AppData\Local\Temp\ae4fnt2w.0.cs(2921,29) : error CS1056: Компиляция преобразования: Непредусмотренный символ \"$\"\r\n-out \"d:\<path>\ODataConnectedService\test\ODataConnectedService.Tests\bin\Debug\test_out.output\" -a !!MetadataDocumentUri!File%3A%5Cd%3A%5CWork%5CMy1%5C1%5CODataConnectedService%5Ctest%5CODataConnectedService.Tests%5Cbin%5CDebug%5Ctest_edmx.edmx -a !!UseDataServiceCollection!False -a !!TargetLanguage!CSharp -a !!NamespacePrefix!NamespacePrefixRepeatWithSchemaNameSpace.Foo1.Foo11.Foo12 -p \"d:\<path>\ODataConnectedService\test\ODataConnectedService.Tests\bin\Debug\" \"d:\<path>\ODataConnectedService\test\ODataConnectedService.Tests\bin\Debug\ODataT4CodeGenerator.tt\""..

#### Version of the Project affected
ODataConnectedService v0.5.1
VisualStudio Version v16.4.3
Microsoft.Odata.Client v7.6.3

#### To Reproduce
1. Run `CodeGenCommandlineSetNamespacePrefixRepeatWithSchemaNameSpace`, `CodeGenCommandlineSetNamespacePrefixWithSingleNamespace` and `CodeGenCommandlineSimpleEdmx` tests
2. See errors

#### Expected behavior
Tests passed successfully.

#### Actual behavior
Tests occur the error.

#### Screenshots
![errors](https://user-images.githubusercontent.com/29679226/76619547-37648880-653c-11ea-9721-8674f9ef8e1e.png)

#### Solution
Probably, to solve this errors, should change in 2921 line of `ODataT4CodeGenerator.ttinclude` file:

```csharp
throw new Exception($"Could not get CLR type name for EDM type '{edmTypeReference.FullName()}'");
```

on

```csharp
throw new Exception(string.Format(CultureInfo.InvariantCulture, "Could not get CLR type name for EDM type '{0}'", edmTypeReference.FullName()));
```

**Comment by paulodero** [comment]
Do you have VS 2015 installed in your machine?

**Comment by unchase** [comment]
> Do you have VS 2015 installed in your machine?

No, only 2017 and 2019.

**Comment by habbes** [comment]
@unchase that's a known bug that'll probably be fixed in an upcoming PR (#27 ). But if the error occurs even when you don't have VS 2015 installed, and just have 2017 and 2019, then I think we have to investigate it further.

**Comment by unchase** [comment]
@habbes, ok, thanks.

**Comment by paulodero** [comment]
@unchase Are you still experiencing this issue? Even without changing the line below?
`throw new Exception($"Could not get CLR type name for EDM type 
 '{edmTypeReference.FullName()}'");`
My tests run both in VS 2017 and VS2019 without changing that line. I think the PR @habbes mentioned fixed it.

**Comment by unchase** [comment]
> @unchase Are you still experiencing this issue? Even without changing the line below?
> `throw new Exception($"Could not get CLR type name for EDM type '{edmTypeReference.FullName()}'");`
> My tests run both in VS 2017 and VS2019 without changing that line. I think the PR @habbes mentioned fixed it.

Yes, I still experiencing this issue.
Because PR by @habbes solve the issue only for **VS Enterprise** edition:

```csharp
string T4TransformToolPathVSVer2019 = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\TextTransform.exe";
```

What about **VS Community** edition that i have?

**Comment by paulodero** [comment]
@unchase Got it. Probably this should be changed to automatically find VS path irrespective of the edition being used.

**Comment by unchase** [comment]
@paulodero Should to search in windows registry to find this path.

**Comment by unchase** [comment]
Alternative way is [to use `vswhere` tool](https://docs.microsoft.com/en-us/visualstudio/install/tools-for-managing-visual-studio-instances?view=vs-2019#detecting-existing-visual-studio-instances).
